# TODO: Create this workflow that should only be triggerable manually (ideally by me only)

name: Build and push docker image

on: workflow_dispatch
  
jobs:
  push_to_gcp:
    name: Builds Docker image and pushes it to GCP Artifact Registry
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Authenticate with GCP
      uses: 'google-github-actions/auth@v2.1.7'
      with:
        gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"

    - name: "Use gcloud CLI"
      run: "gcloud info"

    - name: "Docker auth"
      run: |-
        gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev --quiet

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Build Docker image
      run: docker build --tag quotablegoofs .
        
    - name: Tag Docker image
      with:
        artifact_registry_url: ${{ secrets.ARTIFACT_REGISTRY_URL }}
      run: docker tag quotablegoofs "$artifact_registry_url"

    - name: Push Docker image to GCP
      with:
        artifact_registry_url: ${{ secrets.ARTIFACT_REGISTRY_URL }}
      run: docker push "$artifact_registry_url"/quotablegoofs